# Goal: Fly through the following set of waypoints
float64[] latitudes
float64[] longitudes
float64[] altitudes
---
# Result
bool success
string message
float64 total_time_seconds
---
# Feedback
uint8 current_waypoint_index
uint8 total_waypoints
float64 distance_to_waypoint
